// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6p1N3WmDyJN9iyIxnpGWRFPBkoi76Xsc',
    appId: '1:457292079506:web:8d170ad9c296867f04e14b',
    messagingSenderId: '457292079506',
    projectId: 'budgetmanager-25b0b',
    authDomain: 'budgetmanager-25b0b.firebaseapp.com',
    storageBucket: 'budgetmanager-25b0b.appspot.com',
    measurementId: 'G-EWVF5XSP7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdfBPNU4R_T4vZNMhY-fQ8UqsZYLGjrpU',
    appId: '1:457292079506:android:d237e175e0dd2b4604e14b',
    messagingSenderId: '457292079506',
    projectId: 'budgetmanager-25b0b',
    storageBucket: 'budgetmanager-25b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8lT4YoWkrXf1ysGdhnY1bvYGLG7MEIJA',
    appId: '1:457292079506:ios:231ccfd77580589304e14b',
    messagingSenderId: '457292079506',
    projectId: 'budgetmanager-25b0b',
    storageBucket: 'budgetmanager-25b0b.appspot.com',
    iosBundleId: 'com.example.budgetManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8lT4YoWkrXf1ysGdhnY1bvYGLG7MEIJA',
    appId: '1:457292079506:ios:231ccfd77580589304e14b',
    messagingSenderId: '457292079506',
    projectId: 'budgetmanager-25b0b',
    storageBucket: 'budgetmanager-25b0b.appspot.com',
    iosBundleId: 'com.example.budgetManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6p1N3WmDyJN9iyIxnpGWRFPBkoi76Xsc',
    appId: '1:457292079506:web:c9227ad80dea960904e14b',
    messagingSenderId: '457292079506',
    projectId: 'budgetmanager-25b0b',
    authDomain: 'budgetmanager-25b0b.firebaseapp.com',
    storageBucket: 'budgetmanager-25b0b.appspot.com',
    measurementId: 'G-C1TWQKV3GW',
  );

}